cicd/remove build from ci

diff --git a/.github/workflows/ga-apiplatform.yml b/.github/workflows/ga-apiplatform.yml
--- a/.github/workflows/ga-apiplatform.yml
+++ b/.github/workflows/ga-apiplatform.yml
@@ -1,58 +1,59 @@
-name: apiplatform-github-actions
+# name: apiplatform-github-actions
 
-on:
-  # push:
-  pull_request:
-    branches:
-      - main
-  workflow_dispatch:
+# on:
+#   # push:
+#   pull_request:
+#     branches:
+#       - main
+#   workflow_dispatch:
 
-jobs:
-  ci-apiplatform:
-    name: apiplatform - Build and test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+# jobs:
+#   ci-apiplatform:
+#     name: apiplatform - Build and test
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Pull images
-        run: docker compose pull --ignore-pull-failures || true
+#       - name: Pull images
+#         run: docker compose pull --ignore-pull-failures || true
 
-      - name: Start services
-        run: docker compose up -d
-        # run: docker compose up --build -d
+#       - name: Start services
+#         run: docker compose up -d
+#         # run: docker compose up --build -d
 
-      - name: Wait for services
-        run: |
-          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
-            case $status in
-              starting) sleep 1;;
-              healthy) exit 0;;
-              unhealthy)
-                docker compose ps
-                docker compose logs
-                exit 1
-              ;;
-            esac
-          done
-          exit 1
+#       - name: Wait for services
+#         run: |
+#           while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
+#             case $status in
+#               starting) sleep 1;;
+#               healthy) exit 0;;
+#               unhealthy)
+#                 docker compose ps
+#                 docker compose logs
+#                 exit 1
+#               ;;
+#             esac
+#           done
+#           exit 1
 
-      - name: Check HTTP reachability
-        run: curl -v -o /dev/null http://localhost
+#       - name: Check HTTP reachability
+#         run: curl -v -o /dev/null http://localhost
 
-      - name: Check API reachability
-        run: curl -vk -o /dev/null https://localhost
+#       - name: Check API reachability
+#         run: curl -vk -o /dev/null https://localhost
 
-      - name: Check PWA reachability
-        run: "curl -vk -o /dev/null -H 'Accept: text/html' https://localhost"
+#       - name: Check PWA reachability
+#         run: "curl -vk -o /dev/null -H 'Accept: text/html' https://localhost"
 
-      - name: Create test database
-        run: |
-          docker compose exec php bin/console doctrine:schema:update --force
-          docker compose exec php bin/console doctrine:fixtures:load
+#       - name: Create test database
+#         run: |
+#           docker compose exec php bin/console doctrine:schema:update --force
+#           docker compose exec php bin/console doctrine:fixtures:load
 
-      - name: PHPUnit
-        run: docker compose exec -T php bin/phpunit
+#       - name: PHPUnit
+#         # run: docker compose exec -T php bin/phpunit
+#         run: docker compose exec php bin/phpunit
 
-      # - name: Doctrine Schema Validator
-      #   run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
+#       # - name: Doctrine Schema Validator
+#       #   run: docker compose exec -T php bin/console doctrine:schema:validate --skip-sync
